nome=input("Digite um funcionário:")
empresa=input("Digite a empresa:")
qtde_funcionarios=int(input("Digite a quantidade de funcionários:"))
cargo=input("Digite o cargo:")
mediaSalarial=float(input("Digite a média salarial:"))
print("O funcionário " + nome + " trabalha na empresa " + empresa)
print("A " + empresa + " possui cerca de" , str(qtde_funcionarios) , "funcionários")
print("A função de " + cargo + " tem a média salarial de R$" , str(mediaSalarial))
print("O tipo de dado da variável [nome] é: ",type(nome))
print("O tipo de dado da variável [empresa] é: ",type(empresa))
print("O tipo de dado da variável [qtde_funcioarios] é: ",type(qtde_funcionarios))
print("O tipo de dado da variável [cargo] é: ",type(cargo))
print("O tipo de dado da variável [mediaSalarial] é: ",type(mediaSalarial))
